### ISSUE TITLE
перевод диаграммы diagram_pkce.svg

### ISSUE THREAD

**Issue by unovs** [xsltdev/reactnativedev.ru#13]
в фигме по быстрому перевёл диаграмму. Замени её на странице https://reactnativedev.ru/rn/security/#oauth2 за место diagram_pkce.svg
![diagram_pkce 1](https://github.com/xsltdev/reactnativedev.ru/assets/62508316/bdfff931-3838-468d-9fb7-dfe68f57649a)

**Comment by bndby** [comment]
готово
